/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconAntDesignCheckCircleFilled: typeof import('~icons/ant-design/check-circle-filled.jsx')['default']
  const IconIxErrorFilled: typeof import('~icons/ix/error-filled.jsx')['default']
  const IconLucideChevronDown: typeof import('~icons/lucide/chevron-down.jsx')['default']
  const IconLucideCircle: typeof import('~icons/lucide/circle.jsx')['default']
  const IconLucideSearch: typeof import('~icons/lucide/search.jsx')['default']
  const IconMaterialSymbolsCircle: typeof import('~icons/material-symbols/circle.jsx')['default']
  const tk: typeof import('../../../../../src/localization/translationKeys')['default']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
